# config stuff

port: 9001

database:
  user:     'postgres'
  password: 'postgres'
  host:     'localhost'
  port:     5432
  name:     'cv19makers_vitalox'
  sqlFile:  './../../database/VitalOx.sql'
  query:
    limit: 50

logger:
  path: './logs/'
  level:
    console: 'silly'
    file:    'error'

queues:
    consumer:
      dataProbes:
        ip:        'localhost'
        port:      5672
        user:      'vitalox'
        password:  'vitalox'
        queueName: 'data-open-vitalox-0'
    sender:
      alarms:
        ip:        'localhost'
        port:      5672
        user:      'vitalox'
        password:  'vitalox'
        queueName: 'alarm-open-vitalox-0'
