# config stuff

port: 9001

# expiresIn secods also possible '2h' for expiration in two hours
jwt:
  algorithm: 'HS256'
  expiresIn: '120m'
  secret: '8VmSJ3yW00qgr5kPXpxc/MQr2HISl2RBIpVD/cVg98mPsNmuxP'

database:
  user:     'postgres'
  password: 'postgres'
  host:     'localhost'
  port:     5432
  name:     'cv19makers_vitalox'
  sqlFile:  './../../database/VitalOx.sql'
  query:
    limit: 50
  cache:
    ttl: 2 # minutes

logger:
  path: './logs/'
  level:
    console: 'silly'
    file:    'error'

alarms:
  interval: 5 # minutes

queues:
    consumer:
      dataProbes:
        ip:        'localhost'
        port:      5672
        user:      'vitalox'
        password:  'vitalox'
        queueName: 'data-open-vitalox-0'
    sender:
      alarms:
        ip:        'localhost'
        port:      5672
        user:      'vitalox'
        password:  'vitalox'
        queueName: 'alarm-open-vitalox-0'
